# Generated by Django 5.1.1 on 2024-09-27 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_cart_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suborden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Finalizada'), ('cancelled', 'Cancelada')], default='pending', max_length=10)),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborder', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
