# Generated by Django 5.1.1 on 2024-09-27 09:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_cart_alter_order_user'),
        ('suborders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suborden',
            new_name='Suborder',
        ),
        migrations.RenameField(
            model_name='suborder',
            old_name='orden_id',
            new_name='order_id',
        ),
    ]
