# Generated by Django 5.1.1 on 2024-09-30 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_cart_alter_order_user'),
        ('suborders', '0002_rename_suborden_suborder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='order_id',
        ),
        migrations.AddField(
            model_name='suborder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborders', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_suborder', to=settings.AUTH_USER_MODEL),
        ),
    ]
