# Generated by Django 5.1.1 on 2024-09-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_cart_alter_order_user'),
        ('suborders', '0003_remove_suborder_order_id_suborder_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suborders', to='orders.order'),
        ),
    ]
